# Generated by Django 5.1.1 on 2024-09-11 01:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_custom_user_address_nid_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='nid_model',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='Media/Profile_Pic/NID'),
        ),
        migrations.CreateModel(
            name='Passport_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_number', models.PositiveIntegerField(null=True)),
                ('profile_pic', models.ImageField(null=True, upload_to='Media/Profile_Pic/Passport')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
