# Generated by Django 5.1.1 on 2024-09-11 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_nid_model_profile_pic_passport_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport_model',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.nid_model'),
        ),
    ]
